# Generated by Django 3.1.5 on 2021-03-26 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('description', models.TextField()),
                ('impact', models.TextField()),
                ('category', models.CharField(choices=[('create', 'Create'), ('diversify', 'Diversify'), ('expand', 'Expand'), ('partner', 'Partner')], max_length=9)),
                ('geographic_scope', models.CharField(choices=[('uk_wide', 'UK-wide'), ('england_only', 'England only')], max_length=12)),
                ('supporting_organisations', models.CharField(choices=[('HMT', 'Treasury'), ('DHSC', 'DHSC'), ('BEIS', 'BEIS'), ('DCMS', 'DCMS'), ('DIT', 'DIT'), ('DEFRA', 'DEFRA'), ('CABINET_OFFICE', 'Cabinet Office'), ('MOD', 'MoD'), ('HOME_OFFICE', 'Home Office'), ('FCDO', 'FCDO'), ('DEVOLVED_ADMINISTRATIONS', 'Devolved administrations'), ('DFT', 'DfT')], max_length=24)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('target_completion_date', models.DateField(null=True)),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplyChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('last_submission_date', models.DateField(null=True)),
                ('contact_name', models.CharField(max_length=250)),
                ('contact_email', models.CharField(max_length=250)),
                ('vulnerability_status', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6)),
                ('vulnerability_status_disagree_reason', models.TextField(blank=True)),
                ('risk_severity_status', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6)),
                ('risk_severity_status_disagree_reason', models.TextField(blank=True)),
                ('gov_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_chains', to='accounts.govdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateField(default=datetime.datetime(2021, 3, 26, 17, 0, 40, 348508))),
                ('supply_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('supply_rating_reason', models.TextField(help_text='This field collects information about the characteristics that\n        contribute to the vulnerability of the supply element of the chain.')),
                ('make_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('make_rating_reason', models.TextField(help_text='This field collects information about the characteristics that \n        contribute to the vulnerability of the make element of the chain.')),
                ('receive_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('receive_rating_reason', models.TextField(help_text='This field collects information about the characteristics that \n        contribute to the vulnerability of the receive element of the chain.')),
                ('store_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('store_rating_reason', models.TextField(help_text='This field collects information about the characteristics that \n        contribute to the vulnerability of the store element of the chain.')),
                ('deliver_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('deliver_rating_reason', models.TextField(help_text='This field collects information about the characteristics that \n        contribute to the vulnerability of the deliver element of the chain.')),
                ('supply_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vulnerability_assessment', to='supply_chains.supplychain')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicActionUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('submitted', 'Submitted')], default='in_progress', help_text="The 'completed' and 'in_progress' statuses are used to help\n users know whether they have completed all required fields for an update.\n The 'submitted' status refers to when a user can no longer edit an update.", max_length=11)),
                ('submission_date', models.DateField(null=True)),
                ('content', models.TextField(blank=True)),
                ('implementation_rag_rating', models.CharField(blank=True, choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('reason_for_delays', models.TextField(blank=True)),
                ('strategic_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_updates', to='supply_chains.strategicaction')),
                ('supply_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_updates', to='supply_chains.supplychain')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='strategicaction',
            name='supply_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategic_actions', to='supply_chains.supplychain'),
        ),
        migrations.CreateModel(
            name='ScenarioAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateField(default=datetime.datetime(2021, 3, 26, 17, 0, 40, 348994))),
                ('borders_closed_impact', models.TextField(help_text='This field collects information about the potential impacts that would occur should\n        the borders close.')),
                ('borders_closed_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('storage_full_impact', models.TextField(help_text='This field collects information about the potential impacts that would occur should\n        storage facilities be full.')),
                ('storage_full_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('ports_blocked_impact', models.TextField(help_text='This field collects information about the potential impacts that would occur should\n        the ports be blocked.')),
                ('ports_blocked_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('raw_material_shortage_impact', models.TextField(help_text='This field collects information about the potential impacts that would occur should\n        there be a raw material shortage.')),
                ('raw_material_shortage_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('labour_shortage_impact', models.TextField(help_text='This field collects information about the potential impacts that would occur should\n        there be a labour shortage.')),
                ('labour_shortage_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('demand_spike_impact', models.TextField(help_text='This field collects information about the potential impacts that would occur should\n        the demand spike.')),
                ('demand_spike_rag_rating', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=5)),
                ('supply_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_assessment', to='supply_chains.supplychain')),
            ],
        ),
        migrations.CreateModel(
            name='MaturitySelfAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateField(default=datetime.datetime(2021, 3, 26, 17, 0, 40, 348178))),
                ('maturity_rating_reason', models.TextField()),
                ('maturity_rating_level', models.CharField(choices=[('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3'), ('level_4', 'Level 4'), ('level_5', 'Level 5')], max_length=7)),
                ('supply_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maturity_self_assessment', to='supply_chains.supplychain')),
            ],
        ),
    ]
