# Generated by Django 3.1.5 on 2021-03-29 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturityselfassessment',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scenarioassessment',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vulnerabilityassessment',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
