# Generated by Django 3.1.7 on 2021-04-12 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0002_auto_20210329_1319"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicactionupdate",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
