# Generated by Django 3.1.7 on 2021-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0002_auto_20210329_1319"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicaction",
            name="other_dependencies",
            field=models.TextField(
                blank=True,
                help_text="Any other dependencies or requirements for completing the action.",
            ),
        ),
        migrations.AddField(
            model_name="strategicaction",
            name="specific_related_products",
            field=models.TextField(
                blank=True,
                help_text="Details of specific products within the supply chain which the action applies to, if applicable.",
            ),
        ),
        migrations.AlterField(
            model_name="strategicaction",
            name="supporting_organisations",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HMT", "Treasury"),
                    ("DHSC", "DHSC"),
                    ("BEIS", "BEIS"),
                    ("DCMS", "DCMS"),
                    ("DIT", "DIT"),
                    ("DEFRA", "DEFRA"),
                    ("CABINET_OFFICE", "Cabinet Office"),
                    ("MOD", "MoD"),
                    ("HOME_OFFICE", "Home Office"),
                    ("FCDO", "FCDO"),
                    ("DEVOLVED_ADMINISTRATIONS", "Devolved administrations"),
                    ("DFT", "DfT"),
                ],
                max_length=24,
            ),
        ),
    ]
