# Generated by Django 3.1.8 on 2021-04-22 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0003_update_strategic_action_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="implementation_rag_rating",
            field=models.CharField(
                choices=[("GREEN", "Green"), ("AMBER", "Amber"), ("RED", "Red")],
                default=None,
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="submission_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
