# Generated by Django 3.1.7 on 2021-04-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0004_auto_20210412_1641"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplychain",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
