# Generated by Django 3.1.7 on 2021-04-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0003_update_strategic_action_model"),
        ("supply_chains", "0006_auto_20210413_1332"),
    ]

    operations = []
