# Generated by Django 3.1.7 on 2021-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0008_auto_20210416_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicaction",
            name="archived_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="strategicaction",
            name="archived_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplychain",
            name="archived_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplychain",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="strategicaction",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
