# Generated by Django 3.1.8 on 2021-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0009_merge_20210427_0934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="changed_is_ongoing",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
