# Generated by Django 3.1.8 on 2021-04-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0009_auto_20210426_1251"),
        ("supply_chains", "0010_auto_20210427_1027"),
    ]

    operations = []
