# Generated by Django 3.1.8 on 2021-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0011_merge_20210427_1556"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategicaction",
            name="target_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
