# Generated by Django 3.2.2 on 2021-05-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0014_merge_20210520_1121"),
        ("supply_chains", "0014_sc_archived_reason"),
    ]

    operations = []
