# Generated by Django 3.2.2 on 2021-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0014_merge_20210520_1121"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplychain",
            name="archived_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategicaction",
            name="impact",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategicaction",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplychain",
            name="contact_email",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="supplychain",
            name="contact_name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
