version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: webpack-dev-server
      - dependency-name: ws
    rebase-strategy: disabled