version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "ws"
        versions: ["5.x", "7.4.5"]
      - dependency-name: "webpack-dev-server"
        versions: ["3.x"]
