# Generated by Django 3.1.7 on 2021-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0003_strategicactionupdate_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("submitted", "Submitted"),
                ],
                default="in_progress",
                help_text="The 'completed' and 'in_progress' statuses are used to help\n users know whether they have completed all required fields for an update.\n The 'submitted' status refers to when a user can no longer edit an update.",
                max_length=11,
            ),
        ),
    ]
