# Generated by Django 3.1.8 on 2021-04-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0008_auto_20210416_1420"),
        ("supply_chains", "0005_changed_target_completion_date"),
    ]

    operations = []
