# Generated by Django 3.2.4 on 2021-06-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0020_merge_20210618_0745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplychain",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
    ]
