# Generated by Django 3.2.4 on 2021-08-20 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0022_add_fields_last_modified_20210621_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="date_created",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
