# Generated by Django 3.2.4 on 2021-08-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0023_alter_sau_date_created_with_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicaction",
            name="gsc_notes",
            field=models.TextField(
                blank=True,
                help_text="Free text area to record observations, notes by admin/gsc",
                null=True,
            ),
        ),
    ]
