# Generated by Django 3.2.4 on 2021-09-21 09:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0035_alter_supplychain_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="CountryDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dependency_level",
                    models.CharField(
                        choices=[
                            ("none", "No"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                        ],
                        max_length=9,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_chain_dependencies",
                        to="supply_chains.country",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_dependencies",
                        to="supply_chains.supplychain",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Country dependencies",
                "ordering": ("supply_chain", "country"),
            },
        ),
    ]
