# Generated by Django 3.2.4 on 2021-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0035_alter_supplychain_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenarioassessment",
            name="borders_closed_critical_scenario",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the scenarios envisaged should the lack of storage facilities become critical.",
            ),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="borders_closed_is_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="demand_spike_critical_scenario",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the scenarios envisaged should the demand spike become critical.",
            ),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="demand_spike_is_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="labour_shortage_critical_scenario",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the scenarios envisaged should the labour shortages become critical.",
            ),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="labour_shortage_is_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="ports_blocked_critical_scenario",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the scenarios envisaged should the port blockages become critical.",
            ),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="ports_blocked_is_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="raw_material_shortage_critical_scenario",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the scenarios envisaged should the raw materials shortage become critical.",
            ),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="raw_material_shortage_is_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="storage_full_critical_scenario",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the scenarios envisaged should the lack of storage facilities become critical.",
            ),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="storage_full_is_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="borders_closed_rag_rating",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="demand_spike_rag_rating",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="labour_shortage_rag_rating",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="ports_blocked_rag_rating",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="raw_material_shortage_rag_rating",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="storage_full_rag_rating",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
    ]
