# Generated by Django 3.2.4 on 2021-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0040_alter_supplychainstage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplychainstagesection",
            name="name",
            field=models.CharField(
                choices=[
                    ("overview", "Overview"),
                    ("key products", "Key Products"),
                    ("key services", "Key Services"),
                    ("key activities", "Key Activities"),
                    ("key countries", "Key Countries"),
                    ("key transport points", "Key Transport Points"),
                    ("key companies", "Key Companies"),
                    ("key sectors", "Key Sectors"),
                    ("other relevant information", "Other Relevant Information"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
