# Generated by Django 3.2.5 on 2021-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0041_alter_supplychainstagesection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenarioassessment",
            name="borders_closed_impact",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the potential impacts that would occur should\n        the borders close.",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="borders_closed_rag_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="demand_spike_impact",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the potential impacts that would occur should\n        the demand spike.",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="demand_spike_rag_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="labour_shortage_impact",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the potential impacts that would occur should\n        there be a labour shortage.",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="labour_shortage_rag_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="ports_blocked_impact",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the potential impacts that would occur should\n        the ports be blocked.",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="ports_blocked_rag_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="raw_material_shortage_impact",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the potential impacts that would occur should\n        there be a raw material shortage.",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="raw_material_shortage_rag_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="storage_full_impact",
            field=models.TextField(
                blank=True,
                help_text="This field collects information about the potential impacts that would occur should\n        storage facilities be full.",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="storage_full_rag_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                max_length=5,
            ),
        ),
    ]
