# Generated by Django 3.2.5 on 2021-09-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0042_auto_20210928_1446"),
        ("supply_chains", "0043_make_scenarioassessment_fields_optional"),
    ]

    operations = []
