# Generated by Django 3.2.4 on 2021-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0044_merge_20210928_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplychainumbrella",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
    ]
