# Generated by Django 3.2.4 on 2021-10-06 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0044_merge_20210928_1619"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="deliver_rag_rating",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="deliver_rating_reason",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="make_rag_rating",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="make_rating_reason",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="receive_rag_rating",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="receive_rating_reason",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="store_rag_rating",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="store_rating_reason",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="supply_rag_rating",
        ),
        migrations.RemoveField(
            model_name="vulnerabilityassessment",
            name="supply_rating_reason",
        ),
        migrations.CreateModel(
            name="VulAssessmentSupplyStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "supply_stage_rag_rating",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        help_text="RAG rating for the whole stage.",
                        max_length=5,
                        verbose_name="Supply stage - RAG Rating",
                    ),
                ),
                (
                    "supply_rag_rating_1",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Supply stage 1 - Dependence on foreign suppliers for product - RAG Rating",
                    ),
                ),
                (
                    "supply_stage_summary_1",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Supply stage 1 - Dependence on foreign suppliers for product - Summary",
                    ),
                ),
                (
                    "supply_stage_rationale_1",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Supply stage 1 - Dependence on foreign suppliers for product- Rationale",
                    ),
                ),
                (
                    "supply_rag_rating_2",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Supply stage 2 - Ability to source\xa0alternative products - RAG Rating",
                    ),
                ),
                (
                    "supply_stage_summary_2",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Supply stage 2 - Ability to source\xa0alternative products - Summary",
                    ),
                ),
                (
                    "supply_stage_rationale_2",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Supply stage 2 - Ability to source\xa0alternative products - Rationale",
                    ),
                ),
                (
                    "supply_rag_rating_3",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Supply stage 3 - Resilience of supply base - RAG Rating",
                    ),
                ),
                (
                    "supply_stage_summary_3",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Supply stage 3 - Resilience of supply base - Summary",
                    ),
                ),
                (
                    "supply_stage_rationale_3",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Supply stage 3 - Resilience of supply base - Rationale",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "vulnerability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vulnerability_supply_stage",
                        to="supply_chains.vulnerabilityassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Assessment Supply Stage",
            },
        ),
        migrations.CreateModel(
            name="VulAssessmentStoreStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "store_stage_rag_rating",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        help_text="RAG rating for the whole stage.",
                        max_length=5,
                        verbose_name="Store stage - RAG Rating",
                    ),
                ),
                (
                    "store_rag_rating_11",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Store stage 11 - Size of stock buffer held in UK - RAG Rating",
                    ),
                ),
                (
                    "store_stage_summary_11",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Store stage 11 - Size of stock buffer held in UK - Summary",
                    ),
                ),
                (
                    "store_stage_rationale_11",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Store stage 11 - Size of stock buffer held in UK - Rationale",
                    ),
                ),
                (
                    "store_rag_rating_12",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Store stage 12 - Feasibility of stockpiling - RAG Rating",
                    ),
                ),
                (
                    "store_stage_summary_12",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Store stage 12 - Feasibility of stockpiling - Summary",
                    ),
                ),
                (
                    "store_stage_rationale_12",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Store stage 12 - Feasibility of stockpiling - Rationale",
                    ),
                ),
                (
                    "store_rag_rating_13",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Store stage 13 - Availability of storage in UK - RAG Rating",
                    ),
                ),
                (
                    "store_stage_summary_13",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Store stage 13 - Availability of storage in UK - Summary",
                    ),
                ),
                (
                    "store_stage_rationale_13",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Store stage 13 - Availability of storage in UK - Rationale",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "vulnerability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vulnerability_store_stage",
                        to="supply_chains.vulnerabilityassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Assessment Store Stage",
            },
        ),
        migrations.CreateModel(
            name="VulAssessmentReceiveStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receive_stage_rag_rating",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        help_text="RAG rating for the whole stage.",
                        max_length=5,
                        verbose_name="Receive stage - RAG Rating",
                    ),
                ),
                (
                    "receive_rag_rating_4",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Receive stage 4 - Reliance on long shipping lead times - RAG Rating",
                    ),
                ),
                (
                    "receive_stage_summary_4",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Receive stage 4 - Reliance on long shipping lead times - Summary",
                    ),
                ),
                (
                    "receive_stage_rationale_4",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Receive stage 4 - Reliance on long shipping lead times - Rationale",
                    ),
                ),
                (
                    "receive_rag_rating_5",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Receive stage 5 - Susceptibility to port congestion - RAG Rating",
                    ),
                ),
                (
                    "receive_stage_summary_5",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Receive stage 5 - Susceptibility to port congestion - Summary",
                    ),
                ),
                (
                    "receive_stage_rationale_5",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Receive stage 5 - Susceptibility to port congestion - Rationale",
                    ),
                ),
                (
                    "receive_rag_rating_6",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Receive stage 6 - Size of product stockpile held in UK - RAG Rating",
                    ),
                ),
                (
                    "receive_stage_summary_6",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Receive stage 6 - Size of product stockpile held in UK - Summary",
                    ),
                ),
                (
                    "receive_stage_rationale_6",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Receive stage 6 - Size of product stockpile held in UK - Rationale",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "vulnerability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vulnerability_receive_stage",
                        to="supply_chains.vulnerabilityassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Assessment Receive Stage",
            },
        ),
        migrations.CreateModel(
            name="VulAssessmentMakeStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "make_stage_rag_rating",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        help_text="RAG rating for the whole stage.",
                        max_length=5,
                        verbose_name="Make stage - RAG Rating",
                    ),
                ),
                (
                    "make_rag_rating_7",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Make stage 7 - Ability to substitute planned replacement - RAG Rating",
                    ),
                ),
                (
                    "make_stage_summary_7",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Make stage 7 - Ability to substitute planned replacement - Summary",
                    ),
                ),
                (
                    "make_stage_rationale_7",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Make stage 7 - Ability to substitute planned replacement - Rationale",
                    ),
                ),
                (
                    "make_rag_rating_8",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Make stage 8 - Dependence on foreign contractors - RAG Rating",
                    ),
                ),
                (
                    "make_stage_summary_8",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Make stage 8 - Dependence on foreign contractors - Summary",
                    ),
                ),
                (
                    "make_stage_rationale_8",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Make stage 8 - Dependence on foreign contractors - Rationale",
                    ),
                ),
                (
                    "make_rag_rating_9",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Make stage 9 - Ability to ramp up UK production capacity - RAG Rating",
                    ),
                ),
                (
                    "make_stage_summary_9",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Make stage 9 - Ability to ramp up UK production capacity - Summary",
                    ),
                ),
                (
                    "make_stage_rationale_9",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Make stage 9 - Ability to ramp up UK production capacity - Rationale",
                    ),
                ),
                (
                    "make_rag_rating_10",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Make stage 10 - Susceptibility to labour shortage - RAG Rating",
                    ),
                ),
                (
                    "make_stage_summary_10",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Make stage 10 - Susceptibility to labour shortage - Summary",
                    ),
                ),
                (
                    "make_stage_rationale_10",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Make stage 10 - Susceptibility to labour shortage - Rationale",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "vulnerability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vulnerability_make_stage",
                        to="supply_chains.vulnerabilityassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Assessment Make Stage",
            },
        ),
        migrations.CreateModel(
            name="VulAssessmentDeliverStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deliver_stage_rag_rating",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        help_text="RAG rating for the whole stage.",
                        max_length=5,
                        verbose_name="Deliver stage - RAG Rating",
                    ),
                ),
                (
                    "deliver_rag_rating_14",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("AMBER", "Amber"),
                            ("GREEN", "Green"),
                            ("None", "—"),
                        ],
                        default="None",
                        max_length=5,
                        verbose_name="Deliver stage 14 - Ability to ramp up UK delivery capacity - RAG Rating",
                    ),
                ),
                (
                    "deliver_stage_summary_14",
                    models.TextField(
                        default="",
                        help_text="Summary of supply stage.",
                        verbose_name="Deliver stage 14 - Ability to ramp up UK delivery capacity - Summary",
                    ),
                ),
                (
                    "deliver_stage_rationale_14",
                    models.TextField(
                        default="",
                        help_text="Rationale of supply stage.",
                        verbose_name="Deliver stage 14 - Ability to ramp up UK delivery capacity - Rationale",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "vulnerability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vulnerability_deliver_stage",
                        to="supply_chains.vulnerabilityassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Assessment Deliver Stage",
            },
        ),
    ]
