# Generated by Django 3.2.4 on 2021-10-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0045_supplychainumbrella_slug"),
        ("supply_chains", "0046_alter_vulnerabilityassessment_supply_chain"),
    ]

    operations = []
