version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Copy env file
          command: cp .env.ci .env
      - run:
          name: install webpack 
          command: npm install
      - run:
          name: run webpack
          command: npm run dev
          background: true
      - run:
          name: build docker
          command: make build
      - run:
          name: docker up
          command: make up
          background: true
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: run first use
          command: make first-use
      - run:
          name: load fixture data
          command: make load-data
      - run:
          name: run tests
          command: make test
      - run:
          name: run black (code formatting check)
          command: make black
      - run:
          name: Publish unit test coverage
          command: |
            wget -O codecov.sh https://codecov.io/bash
            bash ./codecov.sh -t ${CODECOV_TOKEN} -s test-reports -f "*.xml"
