# Generated by Django 3.1.8 on 2021-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0004_auto_20210422_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicactionupdate",
            name="changed_target_completion_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="strategicactionupdate",
            name="reason_for_completion_date_change",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="strategicactionupdate",
            name="changed_is_ongoing",
            field=models.BooleanField(default=False),
        ),
    ]
