# Generated by Django 3.1.7 on 2021-04-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0005_supplychain_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicaction",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="strategicactionupdate",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="deliver_rating_reason",
            field=models.TextField(
                help_text="This field collects information about the characteristics that\n        contribute to the vulnerability of the deliver element of the chain."
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_rating_reason",
            field=models.TextField(
                help_text="This field collects information about the characteristics that\n        contribute to the vulnerability of the make element of the chain."
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_rating_reason",
            field=models.TextField(
                help_text="This field collects information about the characteristics that\n        contribute to the vulnerability of the receive element of the chain."
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_rating_reason",
            field=models.TextField(
                help_text="This field collects information about the characteristics that\n        contribute to the vulnerability of the store element of the chain."
            ),
        ),
    ]
