# Generated by Django 3.1.7 on 2021-04-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0007_merge_20210415_1637"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maturityselfassessment",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
