# Generated by Django 3.2.2 on 2021-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0012_auto_20210428_1114"),
    ]

    operations = [
        migrations.RenameField(
            model_name="strategicactionupdate",
            old_name="changed_is_ongoing",
            new_name="changed_value_for_is_ongoing",
        ),
        migrations.RemoveField(
            model_name="strategicactionupdate",
            name="changed_target_completion_date",
        ),
        migrations.AddField(
            model_name="strategicactionupdate",
            name="changed_value_for_target_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="strategicaction",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="implementation_rag_rating",
            field=models.CharField(
                blank=True,
                choices=[("GREEN", "Green"), ("AMBER", "Amber"), ("RED", "Red")],
                default=None,
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplychain",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
