# Generated by Django 3.2.2 on 2021-05-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0010_alter_strategicaction_start_date"),
        ("supply_chains", "0013_auto_20210518_0932"),
    ]

    operations = []
