# Generated by Django 3.2.2 on 2021-06-15 09:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0016_update_sa_status_and_sc_submission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategicaction",
            name="supporting_organisations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("HMT", "Treasury"),
                        ("DHSC", "DHSC"),
                        ("BEIS", "BEIS"),
                        ("DCMS", "DCMS"),
                        ("DIT", "DIT"),
                        ("DEFRA", "DEFRA"),
                        ("CABINET_OFFICE", "Cabinet Office"),
                        ("MOD", "MoD"),
                        ("HOME_OFFICE", "Home Office"),
                        ("FCDO", "FCDO"),
                        ("DEVOLVED_ADMINISTRATIONS", "Devolved administrations"),
                        ("DFT", "DfT"),
                    ],
                    max_length=24,
                ),
                size=None,
            ),
        ),
    ]
