# Generated by Django 3.2.2 on 2021-06-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0018_alter_supplychain_vulnerability_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategicaction",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="supplychain",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
    ]
