# Generated by Django 3.2.2 on 2021-06-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0019_alter_strategicaction_supporting_organisations"),
        ("supply_chains", "0019_extend_slug_limit"),
    ]

    operations = []
