# Generated by Django 3.2.2 on 2021-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0020_merge_20210618_0745"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicaction",
            name="related_to_whole_sc",
            field=models.BooleanField(
                default=False,
                help_text="Strategic action applies/affecting the whole supply chain",
            ),
        ),
        migrations.AlterField(
            model_name="strategicaction",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
