# Generated by Django 3.2.4 on 2021-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0021_alter_supplychain_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="maturityselfassessment",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="strategicaction",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="strategicactionupdate",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="supplychain",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vulnerabilityassessment",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
