# Generated by Django 3.2.4 on 2021-09-09 14:52
import json
import os

from django.db import migrations

from config.settings import BASE_DIR

MIG_DATA_FILE = os.path.join(
    BASE_DIR,
    r"migration_data/sc_description_data_0027.json",
)


def add_supply_chain_description(apps, schema_editor):
    """Source description text from migration data and update the objects"""

    with open(MIG_DATA_FILE, "r") as fp:
        descriptions = json.load(fp)

    SC = apps.get_model("supply_chains", "SupplyChain")

    for supply_chain in SC.objects.all():
        id = str(supply_chain.id)
        if id in descriptions:
            supply_chain.description = descriptions[id]["description"]
            supply_chain.save()


def undo(apps, schema_editor):
    """Nullify the description text"""
    SC = apps.get_model("supply_chains", "SupplyChain")

    for supply_chain in SC.objects.all():
        supply_chain.description = ""
        supply_chain.save()


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0027_add_sc_description"),
    ]

    operations = [
        migrations.RunPython(add_supply_chain_description, undo),
    ]
