# Generated by Django 3.2.4 on 2021-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0027_alter_sc_risk_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="maturityselfassessment",
            name="gsc_last_changed_by",
            field=models.TextField(blank=True, default="", help_text="AAAAAAA"),
        ),
        migrations.AddField(
            model_name="maturityselfassessment",
            name="gsc_review_on",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="maturityselfassessment",
            name="gsc_updated_on",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="gsc_last_changed_by",
            field=models.TextField(blank=True, default="", help_text="AAAAAAA"),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="gsc_review_on",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="scenarioassessment",
            name="gsc_updated_on",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vulnerabilityassessment",
            name="gsc_last_changed_by",
            field=models.TextField(blank=True, default="", help_text="AAAAAAA"),
        ),
        migrations.AddField(
            model_name="vulnerabilityassessment",
            name="gsc_review_on",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vulnerabilityassessment",
            name="gsc_updated_on",
            field=models.DateField(null=True),
        ),
    ]
