# Generated by Django 3.2.4 on 2021-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0028_supplychainstage_supplychainstagesection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplychainstage",
            name="order",
            field=models.PositiveSmallIntegerField(
                default="", help_text="Order number of this stage"
            ),
        ),
    ]
