# Generated by Django 3.2.4 on 2021-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0028_gscupdatemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maturityselfassessment",
            name="gsc_last_changed_by",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The entity responsible for the most recent change",
            ),
        ),
        migrations.AlterField(
            model_name="maturityselfassessment",
            name="gsc_review_on",
            field=models.DateField(
                blank=True,
                help_text="The date when a review should be carried out",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maturityselfassessment",
            name="gsc_updated_on",
            field=models.DateField(
                blank=True, help_text="The date of the most recent change", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="gsc_last_changed_by",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The entity responsible for the most recent change",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="gsc_review_on",
            field=models.DateField(
                blank=True,
                help_text="The date when a review should be carried out",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioassessment",
            name="gsc_updated_on",
            field=models.DateField(
                blank=True, help_text="The date of the most recent change", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="gsc_last_changed_by",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The entity responsible for the most recent change",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="gsc_review_on",
            field=models.DateField(
                blank=True,
                help_text="The date when a review should be carried out",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="gsc_updated_on",
            field=models.DateField(
                blank=True, help_text="The date of the most recent change", null=True
            ),
        ),
    ]
