# Generated by Django 3.2.4 on 2021-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0029_alter_supplychainstage_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplychainstage",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="supplychainstagesection",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
