# Generated by Django 3.2.4 on 2021-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0030_auto_20210916_0759"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplychainstage",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="supplychainstage",
            constraint=models.UniqueConstraint(
                fields=("supply_chain", "order"), name="unique order per supply chain"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplychainstage",
            constraint=models.UniqueConstraint(
                fields=("supply_chain", "name"),
                name="unique stage name per supply chain",
            ),
        ),
    ]
