# Generated by Django 3.2.4 on 2021-09-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0030_stage_models_20210920_1326"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplychainstagesection",
            name="gsc_last_changed_by",
        ),
        migrations.RemoveField(
            model_name="supplychainstagesection",
            name="gsc_review_on",
        ),
        migrations.RemoveField(
            model_name="supplychainstagesection",
            name="gsc_updated_on",
        ),
    ]
