# Generated by Django 3.2.4 on 2021-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0031_auto_20210916_1316"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplychainstagesection",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="supplychainstagesection",
            constraint=models.UniqueConstraint(
                fields=("chain_stage", "name"), name="Unique section within a stage"
            ),
        ),
    ]
