# Generated by Django 3.2.4 on 2021-09-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0032_add_sc_description"),
    ]

    operations = []
