# Generated by Django 3.2.4 on 2021-09-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0036_country_countrydependency"),
        ("supply_chains", "0037_scenarioassessment_onetoone_supply_chain"),
    ]

    operations = []
