# Generated by Django 3.2.4 on 2021-09-28 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_field_last_modified_20210621_1058"),
        ("supply_chains", "0041_alter_supplychainstagesection_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyChainUmbrella",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "gov_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_chain_umbrellas",
                        to="accounts.govdepartment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="supplychain",
            name="supply_chain_umbrella",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supply_chains",
                to="supply_chains.supplychainumbrella",
            ),
        ),
    ]
