# Generated by Django 3.2.4 on 2021-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chains", "0045_update_vulnerability_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="deliver_rag_rating_14",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Deliver stage 14 - Ability to ramp up UK delivery capacity - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="deliver_stage_rationale_14",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Deliver stage 14 - Ability to ramp up UK delivery capacity - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="deliver_stage_summary_14",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Deliver stage 14 - Ability to ramp up UK delivery capacity - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_rag_rating_10",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Make stage 10 - Susceptibility to labour shortage\u200b - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_rag_rating_7",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Make stage 7 - Ability to\u200b substitute planned replacement - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_rag_rating_8",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Make stage 8 - Dependence on foreign contractors\u200b - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_rag_rating_9",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Make stage 9 - Ability to ramp up UK production capacity - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_stage_rationale_10",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Make stage 10 - Susceptibility to labour shortage\u200b - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_stage_rationale_7",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Make stage 7 - Ability to\u200b substitute planned replacement - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_stage_rationale_8",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Make stage 8 - Dependence on foreign contractors\u200b - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_stage_rationale_9",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Make stage 9 - Ability to ramp up UK production capacity - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_stage_summary_10",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Make stage 10 - Susceptibility to labour shortage\u200b - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_stage_summary_7",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Make stage 7 - Ability to\u200b substitute planned replacement - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_stage_summary_8",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Make stage 8 - Dependence on foreign contractors\u200b - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="make_stage_summary_9",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Make stage 9 - Ability to ramp up UK production capacity - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_rag_rating_4",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Receive stage 4 - Reliance on long shipping lead times - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_rag_rating_5",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Receive stage 5 - Susceptibility to port congestion - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_rag_rating_6",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Receive stage 6 - Size of product stockpile held in UK - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_stage_rationale_4",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Receive stage 4 - Reliance on long shipping lead times - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_stage_rationale_5",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Receive stage 5 - Susceptibility to port congestion - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_stage_rationale_6",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Receive stage 6 - Size of product stockpile held in UK - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_stage_summary_4",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Receive stage 4 - Reliance on long shipping lead times - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_stage_summary_5",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Receive stage 5 - Susceptibility to port congestion - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="receive_stage_summary_6",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Receive stage 6 - Size of product stockpile held in UK - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_rag_rating_11",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Store stage 11 - Size of stock buffer held in UK\u200b - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_rag_rating_12",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Store stage 12 - Feasibility of stockpiling\u200b - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_rag_rating_13",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Store stage 13 - Availability of storage in UK\u200b - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_stage_rationale_11",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Store stage 11 - Size of stock buffer held in UK\u200b - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_stage_rationale_12",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Store stage 12 - Feasibility of stockpiling\u200b - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_stage_rationale_13",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Store stage 13 - Availability of storage in UK\u200b - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_stage_summary_11",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Store stage 11 - Size of stock buffer held in UK\u200b - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_stage_summary_12",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Store stage 12 - Feasibility of stockpiling\u200b - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="store_stage_summary_13",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Store stage 13 - Availability of storage in UK\u200b - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_rag_rating_1",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Supply stage 1 - Dependence on foreign suppliers for product - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_rag_rating_2",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Supply stage 2 - Ability to source\xa0alternative\u200b products - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_rag_rating_3",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("GREEN", "Green"),
                    ("None", "—"),
                ],
                default="None",
                max_length=5,
                verbose_name="Supply stage 3 - Resilience of\u200b supply base - RAG Rating",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_stage_rationale_1",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Supply stage 1 - Dependence on foreign suppliers for product- Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_stage_rationale_2",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Supply stage 2 - Ability to source\xa0alternative\u200b products - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_stage_rationale_3",
            field=models.TextField(
                default="",
                help_text="Rationale of supply stage.",
                verbose_name="Supply stage 3 - Resilience of\u200b supply base - Rationale",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_stage_summary_1",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Supply stage 1 - Dependence on foreign suppliers for product - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_stage_summary_2",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Supply stage 2 - Ability to source\xa0alternative\u200b products - Summary",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityassessment",
            name="supply_stage_summary_3",
            field=models.CharField(
                default="",
                help_text="Summary of supply stage.",
                max_length=250,
                verbose_name="Supply stage 3 - Resilience of\u200b supply base - Summary",
            ),
        ),
    ]
