# Generated by Django 3.2.5 on 2021-10-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_govdepartment_visualisation_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0046_alter_vulnerabilityassessment_supply_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychain',
            name='criticality_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Limited'), (2, 'Minor'), (3, 'Moderate'), (4, 'Significant'), (5, 'Catastrophic')], null=True),
        ),
        migrations.CreateModel(
            name='HistoricalSupplyChain',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('last_submission_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250)),
                ('contact_email', models.CharField(blank=True, max_length=250)),
                ('vulnerability_status', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=6)),
                ('vulnerability_status_disagree_reason', models.TextField(blank=True)),
                ('risk_severity_status', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=6)),
                ('risk_severity_status_disagree_reason', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=75, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_reason', models.TextField(blank=True)),
                ('archived_date', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('criticality_rating', models.IntegerField(blank=True, choices=[(1, 'Limited'), (2, 'Minor'), (3, 'Moderate'), (4, 'Significant'), (5, 'Catastrophic')], null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gov_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.govdepartment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supply_chain_umbrella', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supply_chains.supplychainumbrella')),
            ],
            options={
                'verbose_name': 'historical supply chain',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
