# Generated by Django 3.2.5 on 2021-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0047_auto_20211013_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplychain',
            name='gsc_last_changed_by',
            field=models.CharField(blank=True, default='', help_text='The entity responsible for the most recent change', max_length=64, verbose_name='last updated by'),
        ),
        migrations.AddField(
            model_name='historicalsupplychain',
            name='gsc_review_on',
            field=models.DateField(blank=True, help_text='The date when a review should be carried out', null=True, verbose_name='review on'),
        ),
        migrations.AddField(
            model_name='historicalsupplychain',
            name='gsc_updated_on',
            field=models.DateField(blank=True, help_text='The date of the most recent change', null=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='supplychain',
            name='gsc_last_changed_by',
            field=models.CharField(blank=True, default='', help_text='The entity responsible for the most recent change', max_length=64, verbose_name='last updated by'),
        ),
        migrations.AddField(
            model_name='supplychain',
            name='gsc_review_on',
            field=models.DateField(blank=True, help_text='The date when a review should be carried out', null=True, verbose_name='review on'),
        ),
        migrations.AddField(
            model_name='supplychain',
            name='gsc_updated_on',
            field=models.DateField(blank=True, help_text='The date of the most recent change', null=True, verbose_name='last updated'),
        ),
    ]
