# Generated by Django 3.2.5 on 2021-10-20 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_govdepartment_visualisation_url'),
        ('supply_chains', '0047_merge_20211012_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainCriticality',
            fields=[
                ('gsc_last_changed_by', models.CharField(blank=True, default='', help_text='The entity responsible for the most recent change', max_length=64, verbose_name='last updated by')),
                ('gsc_updated_on', models.DateField(blank=True, help_text='The date of the most recent change', null=True, verbose_name='last updated')),
                ('gsc_review_on', models.DateField(blank=True, help_text='The date when a review should be carried out', null=True, verbose_name='review on')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Limited'), (2, 'Minor'), (3, 'Moderate'), (4, 'Significant'), (5, 'Catastrophic')], null=True)),
                ('supply_chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='criticality', serialize=False, to='supply_chains.supplychain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyChainMaturity',
            fields=[
                ('gsc_last_changed_by', models.CharField(blank=True, default='', help_text='The entity responsible for the most recent change', max_length=64, verbose_name='last updated by')),
                ('gsc_updated_on', models.DateField(blank=True, help_text='The date of the most recent change', null=True, verbose_name='last updated')),
                ('gsc_review_on', models.DateField(blank=True, help_text='The date when a review should be carried out', null=True, verbose_name='review on')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], null=True)),
                ('supply_chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='maturity', serialize=False, to='supply_chains.supplychain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supplychain',
            name='criticality_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Limited'), (2, 'Minor'), (3, 'Moderate'), (4, 'Significant'), (5, 'Catastrophic')], null=True),
        ),
        migrations.AddField(
            model_name='supplychain',
            name='gsc_last_changed_by',
            field=models.CharField(blank=True, default='', help_text='The entity responsible for the most recent change', max_length=64, verbose_name='last updated by'),
        ),
        migrations.AddField(
            model_name='supplychain',
            name='gsc_review_on',
            field=models.DateField(blank=True, help_text='The date when a review should be carried out', null=True, verbose_name='review on'),
        ),
        migrations.AddField(
            model_name='supplychain',
            name='gsc_updated_on',
            field=models.DateField(blank=True, help_text='The date of the most recent change', null=True, verbose_name='last updated'),
        ),
        migrations.CreateModel(
            name='HistoricalSupplyChain',
            fields=[
                ('gsc_last_changed_by', models.CharField(blank=True, default='', help_text='The entity responsible for the most recent change', max_length=64, verbose_name='last updated by')),
                ('gsc_updated_on', models.DateField(blank=True, help_text='The date of the most recent change', null=True, verbose_name='last updated')),
                ('gsc_review_on', models.DateField(blank=True, help_text='The date when a review should be carried out', null=True, verbose_name='review on')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('last_submission_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250)),
                ('contact_email', models.CharField(blank=True, max_length=250)),
                ('vulnerability_status', models.CharField(choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=6)),
                ('vulnerability_status_disagree_reason', models.TextField(blank=True)),
                ('risk_severity_status', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=6)),
                ('risk_severity_status_disagree_reason', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=75, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_reason', models.TextField(blank=True)),
                ('archived_date', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('criticality_rating', models.IntegerField(blank=True, choices=[(1, 'Limited'), (2, 'Minor'), (3, 'Moderate'), (4, 'Significant'), (5, 'Catastrophic')], null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gov_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.govdepartment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supply_chain_umbrella', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supply_chains.supplychainumbrella')),
            ],
            options={
                'verbose_name': 'historical supply chain',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
