# Generated by Django 3.2.2 on 2021-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_dit_govdepartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_feedback_emails",
            field=models.BooleanField(
                default=False,
                help_text="If True, feedback emails from other users will be sent to the address in the user's email field.",
            ),
        ),
    ]
