# Generated by Django 3.2.4 on 2021-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_receive_feedback_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="govdepartment",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
