# Generated by Django 3.2.4 on 2021-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_field_last_modified_20210621_1058"),
    ]

    operations = [
        migrations.AddField(
            model_name="govdepartment",
            name="visualisation_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of the visualisation page for this department",
                verbose_name="Visualisation URL",
            ),
        ),
    ]
