# Generated by Django 3.1.5 on 2021-02-11 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supply_chain_update", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MonthlyUpdate",
            new_name="StrategicActionUpdate",
        ),
    ]
