# Generated by Django 3.1.5 on 2021-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain_update", "0003_replace_is_draft_with_status_in_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="implementation_rag_rating",
            field=models.CharField(
                blank=True,
                choices=[("RED", "Red"), ("AMBER", "Amber"), ("GREEN", "Green")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="reason_for_delays",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategicactionupdate",
            name="submission_date",
            field=models.DateField(null=True),
        ),
    ]
